[project]
name = "advent-of-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firecrawl-py>=4.12.0",
    "google-adk>=1.21.0",
    "google-genai>=1.55.0",
]
